name: Fetch MEXC Popular Symbols Hourly

on:
  schedule:
    - cron: '7 * * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリをチェックアウト（push許可付き）
        uses: actions/checkout@v3
        with:
          persist-credentials: true  # ✅ これが重要！

      - name: Pythonをセットアップ
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 依存パッケージをインストール
        run: pip install -r requirements.txt

      - name: スクリプトを実行
        run: python fetch_rankings.py

      - name: 結果をコミット＆プッシュ
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add rankings.csv
          git commit -m "Update rankings $(date -u +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push

          git push https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git HEAD:main


